name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # push image to Docker Hub
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terrascan
      uses: actions/checkout@v1

    - name: Build Terrascan docker image
      run: make docker-build

    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u accurics --password-stdin

    - name: Push Terrascan latest tag docker image
      run: make docker-push-latest-tag
